src/ecommerce/ArticleBundle/Entity/Image.php
<?php

namespace ecommerce\ArticleBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
// N'oubliez pas ce use :
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="ecommerce\ArticleBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image {

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $url
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string $alt
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;
    public $file;
    // On ajoute cet attribut pour y stocker le nom du fichier temporairement
    private $tempFilename;

    // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
    public function setFile(UploadedFile $file) {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if (null !== $this->url) {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;

            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload() {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
            return;
        }

        // Le nom du fichier est son id, on doit juste stocker également son extension
        // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
        $this->url = $this->file->guessExtension();

        // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload() {
        // Si jamais il n'y a pas de fichier (champ facultatif)
        if (null === $this->file) {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
                $this->getUploadRootDir(), // Le répertoire de destination
                $this->id . '.' . $this->url   // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload() {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload() {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir() {
        // On retourne le chemin relatif vers l'image pour un navigateur
        return 'uploads/img';
    }

    protected function getUploadRootDir() {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    public function getWebPath() {
        return $this->getUploadDir() . '/' . $this->getId() . '.' . $this->getUrl();
    }


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string 
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string 
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

src/ecommerce/ArticleBundle/Controller/ArticleController.php
<?php

// src/ecommerce/ArticleBundle/Controller/ArticleController.php

namespace ecommerce\ArticleBundle\Controller;

//namespace ecommerce\UserBundle\Controller;

use ecommerce\ArticleBundle\Entity\Category;
use ecommerce\ArticleBundle\Entity\Comment;
use ecommerce\ArticleBundle\Entity\Review;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use ecommerce\ArticleBundle\Entity\Article;
use ecommerce\ArticleBundle\Entity\Genre;
use ecommerce\ArticleBundle\Entity\Search;
use ecommerce\ArticleBundle\Entity\Cart;
use ecommerce\UserBundle\Entity\User;
use ecommerce\ArticleBundle\Form\ArticleType;
use ecommerce\ArticleBundle\Form\CommentType;
use ecommerce\ArticleBundle\Form\ReviewType;
use ecommerce\ArticleBundle\Form\SearchType;
use ecommerce\ArticleBundle\Form\CartType;

class ArticleController extends Controller
{
    /*
     * Affichage de tous les articles selon la catégorie sélectionnée
     *
     * */
    public function categoryAction(Category $category, $numberItemsPerPage, $page)
    {
        if ($category == null) {
            return $this->redirect($this->generateUrl('ecommerce_accueil_error404'));
        }

        // Sélection des articles de la catégorie sélectionnée
        $articles = $this->getDoctrine()
            ->getManager()
            ->getRepository('ecommerceArticleBundle:Article')
            ->getArticlesByCategory($numberItemsPerPage, $page, $category);

        $categories = $this->getDoctrine()
            ->getManager()
            ->getRepository('ecommerceArticleBundle:Category')
            ->getCategories();

        return $this->render('ecommerceArticleBundle:Article:category.html.twig', array(
            'articles' => $articles,
            'category' => $category,
            'categories' => $categories,
            'page' => $page,
            'numberItemsPerPage' => $numberItemsPerPage,
            'nombrePage' => ceil(count($articles) / $numberItemsPerPage)
        ));
    }

    /*
     * Affichage de tous les articles selon le genre sélectionné
     *
     * */
    public function genreAction(Genre $genre, $numberItemsPerPage, $page)
    {
        if ($genre == null) {
            return $this->redirect($this->generateUrl('ecommerce_accueil_error404'));
        }

        // Sélection des articles de la catégorie sélectionnée
        $articles = $this->getDoctrine()
            ->getManager()
            ->getRepository('ecommerceArticleBundle:Article')
            ->getArticles($numberItemsPerPage, $page, $genre);

        $categories = $this->getDoctrine()
            ->getManager()
            ->getRepository('ecommerceArticleBundle:Category')
            ->getCategories();

        return $this->render('ecommerceArticleBundle:Article:genre.html.twig', array(
            'articles' => $articles,
            'genre' => $genre,
            'categories' => $categories,
            'page' => $page,
            'numberItemsPerPage' => $numberItemsPerPage,
            'nombrePage' => ceil(count($articles) / $numberItemsPerPage)
        ));
    }

    /*
     * Formulaire pour la création d'un article
     *
     * */
    public function createAction()
    {
        // On vérifie si l'utilisateur est connecté, sinon on le redirige sur le formulaire de connection
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw $this->createAccessDeniedException();
        }

        $article = new Article;

        // On crée le formulaire grâce à l'ArticleType
        $form = $this->createForm(new ArticleType(), $article);

        // On récupère la requête
        $request = $this->getRequest();

        // On vérifie qu'elle est de type POST
        if ($request->getMethod() == 'POST') {
            // On fait le lien Requête <-> Formulaire
            $form->bind($request);

            // On vérifie que les valeurs entrées sont correctes
            if ($form->isValid()) {
                $user = $this->getUser();
                $article->setUser($user);
                // On enregistre notre objet $article dans la base de données
                $em = $this->getDoctrine()->getManager();
                $em->persist($article);
                $em->flush();

                // On définit un message flash
//                $this->get('session')->getFlashBag()->add('info', 'Article bien ajouté');

                // On redirige vers la page de visualisation de l'article nouvellement créé
                return $this->redirect($this->generateUrl('ecommerce_article_detail', array('id' => $article->getId(), 'slug' => $article->getSlug())));
            }
        }

        return $this->render('ecommerceArticleBundle:Article:create.html.twig', array('form' => $form->createView(),));
    }

    /*
     * Affichage des détails de l'article sélectionné
     *
     * */
    public function detailAction(Article $article)
    {
        $user = $article->getUser();
        $note = $user->getNote();

        $comment = new Comment();
        // On crée le formulaire grâce à CommentType
        $form = $this->createForm(new CommentType(), $comment);

        $cart = new Cart();
        // On crée le formulaire ici
        $form_cart = $this->createForm(new CartType(), $cart);

        // On récupère la requête
        $request = $this->getRequest();

        // On vérifie qu'elle est de type POST
        if ($request->getMethod() == 'POST') {
            // On fait le lien Requête <-> Formulaire
            $form->bind($request);

            // On vérifie que les valeurs entrées sont correctes
            if ($form->isValid()) {
                $author = $this->getUser();
                $comment->setAuthor($author);
                $comment->setArticle($article);
                // On enregistre notre objet $comment dans la base de données
                $em = $this->getDoctrine()->getManager();
                $em->persist($comment);
                $em->flush();


                //On pourrait envoyer ici une notification à l'utilisateur.
                /*$mailer = $this->get('mailer');

                $message = \Swift_Message::newInstance()
                    ->setSubject('Hello Tootiye')
                    ->setFrom('tootiye@gmail.com')
                    ->setTo('ipanga@outlook.fr')
                    ->setBody($this->renderView('ecommerceAccueilBundle:Accueil:contact.html.twig'))
                ;
                $mailer->send($message);*/

                // On définit un message flash
//                $this->get('session')->getFlashBag()->add('info', 'Commentaire bien ajouté');

                // On redirige vers la page de visualisation de l'article où on vient de commenter
                return $this->redirect($this->generateUrl('ecommerce_article_detail', array('id' => $article->getId(), 'slug' => $article->getSlug())));
            }
        }

        // On récupère ici tous les commentaires de l'article
        $comments = $this->getDoctrine()
            ->getManager()
            ->getRepository('ecommerceArticleBundle:Comment')
            ->getProductComments($article);

        $categories = $this->getDoctrine()
            ->getManager()
            ->getRepository('ecommerceArticleBundle:Category')
            ->getCategories();

        return $this->render('ecommerceArticleBundle:Article:detail.html.twig',
            array(
                'article' => $article,
                'note' => $note,
                'comments' => $comments,
                'categories' => $categories,
                'form' => $form->createView(),
                'form_cart' => $form_cart->createView(),
            )
        );
    }

    /*
     * Ajout de l'article au panier
     *
     * */
    public function cartAction(Article $article)
    {
        $cart = new Cart();
        // On crée le formulaire ici
        $form = $this->createForm(new CartType(), $cart);

        // On récupère la requête
        $request = $this->getRequest();

        // On vérifie qu'elle est de type POST
        if ($request->getMethod() == 'POST') {
            // On fait le lien Requête <-> Formulaire
            $form->bind($request);

            // On vérifie que les valeurs entrées sont correctes
            if ($form->isValid()) {
                $user = $this->getUser();
                $cart->setUser($user);
                $cart->setArticle($article);
                $cart->setUnitPrice($article->getPrice());
                $cart->setImage($article->getImage());
                $cart->setTotalPrice($article->getPrice() * $cart->getQuantity());
                $cart->setSeller($article->getUser());
                // On enregistre notre objet $review dans la base de données
                $em = $this->getDoctrine()->getManager();
                $em->persist($cart);
                $em->flush();

                // On définit un message flash
                $this->get('session')->getFlashBag()->add('info', 'Le produit a ete ajouté au panier');

                // On redirige vers la page de visualisation de l'article modifié
                return $this->redirect($this->generateUrl('ecommerce_article_detail', array('id' => $article->getId(), 'slug' => $article->getSlug())));
            }
        }

        return $this->redirect($this->generateUrl('ecommerce_article_detail', array('id' => $article->getId(), 'slug' => $article->getSlug())));
    }

    /*
     * Voir le panier
     *
     * */
    public function cartViewAction(User $user1)
    {
        $user = $this->getUser();
        // On vérifie si l'utilisateur est connecté, sinon on le redirige sur le formulaire de connection
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw $this->createAccessDeniedException();
        }
        // On vérifie si l'utilisateur n'essaie pas de voir un panier qui ne lui appartient pas
        // Si c'est le cas, on va le rediriger sur une page d'erreur

src/ecommerce/ArticleBundle/Resources/views/Article/delete.html.twig
{# src/ecommerce/AccueilBundle/Resources/views/Accueil/publications.html.twig #}

{% extends "ecommerceAccueilBundle::layout.html.twig" %}

{% block titre %}
    Mes articles - {{ parent() }}
{% endblock %}

{% block contenu_accueil %}

    <section id="yt_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="breadcrumb">
                        <li><a href="{{ path('ecommerce_accueil_accueil') }}">Accueil</a>
                        </li>
                        <li><a href="{{ path('ecommerce_article_publications') }}">Mes Produits</a>
                        </li>
                        <li>Supprimer Produit</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container">

        <div class="col-md-8 col-md-offset-2" id="basket">

            <div class="box">

                <h1 class="text-center">Supprimer le produit</h1>

                <hr>

                <p class="text-center">
                    Etes-vous certain de vouloir supprimer le produit <strong>"{{ article.getNameItem() }}"</strong> ?
                </p>


                <hr>

                <form action="{{ path('ecommerce_article_delete', {'id': article.id}) }}"
                      method="POST" {{ form_enctype(form) }}>
                    <div class="box-footer">
                        <div class="pull-left">
                            <a href="{{ path('ecommerce_article_publications') }}" class="btn btn-info"><i
                                        class="fa fa-chevron-left"></i> Retour à la liste d'articles</a>
                        </div>
                        <div class="pull-right">
                            <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Confirmer
                                supression <i class="fa fa-chevron-right"></i>
                            </button>
                        </div>
                    </div>
                    {{ form_rest(form) }}
                </form>


            </div>
            <!-- /.box -->


        </div>
        <!-- /.col-md-12 -->

    </div>
    <!-- /.container -->

    <br><br>

{% endblock %}

src/ecommerce/ArticleBundle/Resources/views/Article/detail_genre_panel.html.twig
{# src/ecommerce/ArticleBundle/Resources/views/Article/detail_panel.html.twig #}

<!-- *** MENUS AND FILTERS ***
_________________________________________________________ -->


{#<div class="panel panel-default sidebar-menu">

    <div class="panel-heading">
        <h3 class="panel-title">Toutes les catégories</h3>
    </div>

    <div class="panel-body">
        <ul class="nav nav-pills nav-stacked category-menu">
            {% for categoryP in categories %}
                <li {% if article.genre.category == categoryP %}class="active"{% endif %}>
                    <a href="{{ path('ecommerce_article_cat', {'id': categoryP.id}) }}">{{ categoryP.name }}</a>
                    {% if article.genre.category == categoryP %}
                        <ul>
                            {% for genre_cate in categoryP.genres %}
                                <li>
                                    #}{#il faut optimiser la ligne ci-dessous#}{#
                                    <a href="{{ path('ecommerce_article_categorie', {'id': genre_cate.id}) }}">{{ genre_cate.name }}
                                        <span class="badge pull-right">{{ genre_cate.articles.count }}</span></a>
                                    #}{#<a href="{{ path('ecommerce_article_categorie', {'id': genre_cate.id}) }}">{{ genre_cate.name }}</a>#}{#
                                </li>
                            {% else %}
                                <li>
                                    <a href="#">Pas encore de catégories !</a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                </li>
            {% else %}
                <h4>Pas encore de catégorie</h4>
            {% endfor %}
        </ul>
    </div>
</div>#}

<div class="module block_category">
    <h3 class="modtitle">
        Categories </h3>
    <div class="modcontent box-content">
        <ul class="list-group">
            {% for categoryP in categories %}
                <li {% if article.genre.category == categoryP %}class="hadchild"{% endif %}>
                    <a href="{{ path('ecommerce_article_cat', {'id': categoryP.id}) }}"
                       class="list-group-item ">
                        <span>{{ categoryP.name }}</span>
                    </a>
                    <span {% if article.genre.category == categoryP %}class="button-view  ttopen  "
                          {% else %}class="button-view  ttclose  "{% endif %}>view</span>
                    <ul {% if article.genre.category == categoryP %}style="display: block;"
                        {% else %}style="display: none;"{% endif %}>
                        {% for genre_cate in categoryP.genres %}
                            <li>
                                <a href="{{ path('ecommerce_article_categorie', {'id': genre_cate.id}) }}"
                                   class="list-group-item">
                                    <span>&nbsp;&nbsp;&nbsp; {{ genre_cate.name }}</span>
                                </a>
                            </li>
                        {% else %}
                            <li>
                                <a href="#">Pas encore de catégories !</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% else %}
                <h4>Pas encore de catégorie</h4>
            {% endfor %}
        </ul>
    </div>
</div>
<script type="text/javascript">

    $(document).ready(function () {
        $('span.button-view').click(function () {
            if ($(this).hasClass('ttopen')) {
                varche = true
            } else {
                varche = false
            }
            ;
            if (varche == false) {
                $(this).addClass("ttopen");
                $(this).removeClass("ttclose");
                $(this).parent().find('ul').slideDown();
                varche = true;
            } else {
                $(this).removeClass("ttopen");
                $(this).addClass("ttclose");
                $(this).parent().find('ul').slideUp();
                varche = false;
            }
        });
    });

</script>

src/ecommerce/ArticleBundle/Resources/views/Article/publications.html.twig
{# src/ecommerce/AccueilBundle/Resources/views/Accueil/publications.html.twig #}

{% extends "ecommerceAccueilBundle::layout.html.twig" %}

{% block titre %}
    Mes articles - {{ parent() }}
{% endblock %}

{% block contenu_accueil %}

    <section id="yt_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <ul class="breadcrumb">
                        <li><a href="{{ path('ecommerce_accueil_accueil') }}">Accueil</a>
                        </li>
                        <li>Mes Produits</li>
                    </ul>
                </div>
            </div>
        </div>
    </section>

    <div class="container">
        <h1>Mes Produits
        </h1>

        <!-- Filters -->
        <div class="product-filter product-filter-bottom filters-panel" style="float: left; width: 100%;">

            {#<div class="view-mode hidden-sm hidden-xs">
                <div class="list-view">
                    <button class="btn btn-default grid active" data-view="grid"><i
                                class="fa fa-th-large"></i></button>
                    <button class="btn btn-default list" data-view="list"><i class="fa fa-th-list"></i>
                    </button>
                </div>
            </div>#}
            <div class="short-by-show text-center ">
                <div class="form-group">
                    Affichage de {% if page == nombrePage %}
                        {{ articles.count }}
                    {% else %}
                        {{ page * numberItemsPerPage }}
                    {% endif %} sur {{ articles.count }} produits({{ nombrePage }} Pages)
                </div>
            </div>


            <div class="box-pagination text-right">
                <ul class="pagination">
                    {#On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b#}
                    {% for p in range(1, nombrePage) %}
                        {% if p == page %}
                            <li class="active">
                                <span>{{ p }}</span>
                            </li>
                        {% else %}
                            <li>
                                <a href="{{ path('ecommerce_article_publications', {'page': p}) }}">{{ p }}</a>
                            </li>
                        {% endif %}

                    {% endfor %}
                    <li>
                        <a href="{{ path('ecommerce_article_publications', {'page': nombrePage}) }}">
                            <i class="fa fa-angle-double-right"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- //end Filters -->

        <div class="row">
            <div id="content" class="col-sm-12">

                <form action="#" method="post" enctype="multipart/form-data">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <td class="text-center">Image</td>
                                <td class="text-left">Nom du Produit</td>
                                <td class="text-left">Etat</td>
                                <td class="text-right">Prix Unitaire</td>
                                <td class="text-left">Quantité</td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for article in articles %}
                                <tr>
                                    <td class="text-center">
                                        <a href="{{ path('ecommerce_article_detail', {'id': article.id, 'slug':article.slug}) }}">
                                            {% if article.image is not null %}
                                                <img itemprop="image"
                                                     src="{{ asset(article.image.webPath|imagine_filter('my_thumb')) }}"
                                                     alt="{{ article.getNameItem() }}"
                                                     title="{{ article.getNameItem() }}"
                                                     class="img-thumbnail" width="60">
                                            {% else %}
                                                <img src="{{ asset('img/default_profile.jpg'|imagine_filter('my_thumb')) }}"
                                                     alt="{{ article.getNameItem() }}"
                                                     title="{{ article.getNameItem() }}" class="img-thumbnail"
                                                     width="60">
                                            {% endif %}
                                            {#<img src="Shopping%20Cart_files/28-60x60.png" alt="Bikum masen dumas chuka" title="Bikum masen dumas chuka" class="img-thumbnail">#}
                                        </a>
                                    </td>
                                    <td class="text-left">
                                        <a href="{{ path('ecommerce_article_detail', {'id': article.getId(), 'slug':article.getSlug()}) }}">
                                            {{ article.getNameItem() }}
                                        </a>
                                    </td>
                                    <td class="text-left">{{ article.getQuality() }}</td>
                                    <td class="text-right">{{ article.getPrice()|number_format(0, ',', '.') }}$</td>

                                    <td class="text-left">
                                        <div class="input-group btn-block" style="max-width: 150px;">
                                            <input name="quantity[340]" value="{{ article.getQuantity() }}" size="1"
                                                   class="form-control quaility" type="text" disabled>

                                        <span class="input-group-btn">

                                            <a href="{{ path('ecommerce_article_edit', {'id': article.id}) }}"
                                               data-original-title="Modifier le produit" type="button"
                                               data-toggle="tooltip" title="Modifier le produit" class="btn btn-warning"
                                               role="button">
                                                <i class="fa fa-refresh" style="color: white"></i>
                                            </a>
                                            <a href="{{ path('ecommerce_article_delete', {'id': article.id}) }}"
                                               data-original-title="Supprimer le produit" type="button"
                                               data-toggle="tooltip" title="Supprimer le produit" class="btn btn-danger"
                                               role="button">
                                                <i class="fa fa-trash-o" aria-hidden="true" style="color: white"></i>
                                            </a>


                                        </span>

                                        </div>
                                    </td>

                                </tr>
                            {% else %}
                                <h4>Pas encore de produit</h4>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </form>

                {#<br><br>#}
                <!-- Filters -->
                <div class="product-filter product-filter-bottom filters-panel" style="float: left; width: 100%;">

                    {#<div class="view-mode hidden-sm hidden-xs">
                        <div class="list-view">
                            <button class="btn btn-default grid active" data-view="grid"><i
                                        class="fa fa-th-large"></i></button>
                            <button class="btn btn-default list" data-view="list"><i class="fa fa-th-list"></i>
                            </button>
                        </div>
                    </div>#}
                    <div class="short-by-show text-center ">
                        <div class="form-group">
                            Affichage de {% if page == nombrePage %}
                                {{ articles.count }}
                            {% else %}
                                {{ page * numberItemsPerPage }}
                            {% endif %} sur {{ articles.count }} produits({{ nombrePage }} Pages)
                        </div>
                    </div>


                    <div class="box-pagination text-right">
                        <ul class="pagination">
                            {#On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b#}
                            {% for p in range(1, nombrePage) %}
                                {% if p == page %}
                                    <li class="active">
                                        <span>{{ p }}</span>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="{{ path('ecommerce_article_publications', {'page': p}) }}">{{ p }}</a>
                                    </li>
                                {% endif %}

                            {% endfor %}
                            <li>
                                <a href="{{ path('ecommerce_article_publications', {'page': nombrePage}) }}">
                                    <i class="fa fa-angle-double-right"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- //end Filters -->


            </div>
        </div>

        <br>
    </div>

{% endblock %}